### ISSUE TITLE
Add coloured edge

### ISSUE THREAD

**Issue by donnachakirk** [dfm/daft#66]
Hi,
I really like daft & have begun to play around with it. I'm just trying to do something really simple explaining the inputs needed to model an NFW halo.

I've got a (probably really simple) question, I'd like to colour some of my lines but I'm not quite sure to how to do this with pgm.add_edge? 
daft.Edge doesn't seem to nest like pgm.add_node(daft.Node())?
i.e. I get errors if I try pgn.add_edge(daft.Edge())

![flowchart](https://f.cloud.github.com/assets/3702881/2310273/25998160-a2e1-11e3-9254-68690a7de1a7.png)

**Comment by davidwhogg** [comment]
This is related to #87

**Comment by dsfulf** [comment]
This is fixed by #106.

Using [this example](http://daft-pgm.org/examples/exoplanets/):

from matplotlib import rc
rc("font", family="serif", size=12)
rc("text", usetex=True)

import daft

\# Colors.
p_color = {"ec": "#46a546"}
s_color = {"ec": "#f89406"}

pgm = daft.PGM([3.6, 3.5], origin=[0.7, 0])

n = daft.Node("phi", r"$\phi$", 1, 3, plot_params=s_color)
n.va = "baseline"
pgm.add_node(n)
pgm.add_node(daft.Node("speckle_coeff", r"$z_i$", 2, 3, plot_params=s_color))
pgm.add_node(daft.Node("speckle_img", r"$x_i$", 2, 2, plot_params=s_color))

pgm.add_node(daft.Node("spec", r"$s$", 4, 3, plot_params=p_color))
pgm.add_node(daft.Node("shape", r"$g$", 4, 2, plot_params=p_color))
pgm.add_node(daft.Node("planet_pos", r"$\mu_i$", 3, 3, plot_params=p_color))
pgm.add_node(daft.Node("planet_img", r"$p_i$", 3, 2, plot_params=p_color))

pgm.add_node(daft.Node("pixels", r"$y_i ^j$", 2.5, 1, observed=True))

\# Edges.
p_color.update({"fc": "#46a546"})
s_color.update({"fc": "#f89406"})
pgm.add_edge("phi", "speckle_coeff"**, plot_params=s_color**)
pgm.add_edge("speckle_coeff", "speckle_img"**, plot_params=s_color**)
pgm.add_edge("speckle_img", "pixels")

pgm.add_edge("spec", "planet_img"**, plot_params=p_color**)
pgm.add_edge("shape", "planet_img"**, plot_params=p_color**)
pgm.add_edge("planet_pos", "planet_img"**, plot_params=p_color**)
pgm.add_edge("planet_img", "pixels")

\# And a plate.
pgm.add_plate(daft.Plate([1.5, 0.2, 2, 3.2], label=r"exposure $i$",
    shift=-0.1))
pgm.add_plate(daft.Plate([2, 0.5, 1, 1], label=r"pixel $j$",
    shift=-0.1))

\# Render and save.
pgm.render()
pgm.figure.savefig("exoplanets.pdf")
pgm.figure.savefig("exoplanets.png", dpi=150)

![exoplanets](https://user-images.githubusercontent.com/8421927/50742847-e50c3700-11d5-11e9-9fc0-89ce7927ddd4.png)

**Comment by davidwhogg** [comment]
I'm closing this; reopen if you still have issues
