### ISSUE TITLE
Generate inline graph in jupyter notebook?

### ISSUE THREAD

**Issue by bnlove** [dfm/daft#84]
Can a daft graph be rendered as an inline graphic in a jupyter notebook?

**Comment by drphilmarshall** [comment]
I have found that while yes, daft graphs can be rendered inline, it's
actually better to make the PNG file and then display it - because a) it
comes out bigger (or rather, the size you want it to be) and b) you have
the PNG saved as well.

[Here's an example](
https://github.com/drphilmarshall/StatisticalMethods/blob/master/examples/SDSScatalog/FirstPGM.ipynb)
from a class I taught using notebooks.

**Comment by bnlove** [comment]
Thank you, thank you, thank you!!  This is exactly what I needed.

**Comment by davidwhogg** [comment]
@bnlove if that solves your problem, please close this issue.  Or reformulate it.
